### PR TITLE
transaction add drawer fix

### LINKED ISSUE #37: Drawer stays open when adding a transaction
I added this bug in as a surprise feature...
No uh... this happened because I wanted to give feedback when a form has invalid values, but could not find out how to get the event when a form is successful

### PR DESCRIPTION
**Pull request by SuperRonanCraft**
I only know how to fix this using multiple effects, if ya got ideas how to better this, let me know!

### CODE REVIEW

File: src/lib/components/transaction/add-transaction-form.svelte [hunk 1]
```diff
@@ -26,6 +25,9 @@
 	$effect(() => {
 		if (submitted) error = createNewTransaction.result?.error;
 	});
+	$effect(() => {
```
Comment (hugo-hsi-dev) [inline src/lib/components/transaction/add-transaction-form.svelte:28]: You could do these effects in the ...createNewTransaction.enhance() callback below.
